---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)
source('../scripts/utils.R')

#df <- read.csv('../data/Indicators.csv')
#temp <- df %>% select(CountryName,IndicatorName,Value)
#head(temp)

```
```{r}
library(data.table)
data <- fread("../data/Indicators.csv")
life_df <- subset(df,grepl('life',IndicatorName,ignore.case=TRUE))
items <- unique(life_df$IndicatorName)
print(items)

```

```{r}

```


```{r}

```

```{r}
library(plotly)
plot_ly(type = 'scatter',mode='markers') %>%
  add_trace(
            x=life_analysis_female_df$mean,
            y=life_analysis_female_df$sd,
            hoverinfo=life_analysis_female_df$CountryCode,
            text= life_analysis_female_df$CountryCode)
```

```{r}

sle_female_life_df <- female_life_df %>% filter(CountryCode == 'SLE')
country_name = sle_female_life_df$CountryName[1]
print(sle_female_life_df)
plot_ly(x=sle_female_life_df$Year,y=sle_female_life_df$Value,type = 'scatter',mode='markers') %>%
  layout(
            title ='Life Expectancy of Women in Sierra Leone')
            

```





```{r}

country = 'IRQ'
analyse(life_df,items[1],country )
analyse(life_df,items[2],country)
analyse(life_df,items[3],country )

```
```{r}

country = 'IRN'
analyse(life_df,items[1],country )
analyse(life_df,items[2],country)
analyse(life_df,items[3],country )
analyse(life_df,items[4],country)
analyse(life_df,items[5],country )


```
```{r}
country = 'SLE'
analyse(life_df,items[1],country )
analyse(life_df,items[2],country)
analyse(life_df,items[3],country )

```

```{r}
country = 'SMR'
analyse(life_df,items[1],country )
analyse(life_df,items[2],country)
analyse(life_df,items[3],country )
analyse(life_df,items[4],country)
analyse(life_df,items[5],country )


```

```{r}
get_corr<- function(df,value1,value2,country)
{
  male_df = analysis_df(df,value2,country)$Value
  female_df = analysis_df(df,value1,country)$Value
  return (cor(male_df,female_df))
}


get_angle<- function(df,value1,value2,country)
{
  return( acos(get_corr(df,value1,value2,country)))
}

```
```{r}
unique_countries = unique(df$CountryCode)
```

```{r}

for(country in unique_countries){
   
  print(c(get_corr(life_df,items[1],items[2],country ),country)   )
}

```

```{r}
analyse(life_df,items[1],items[2],'RUS')
```

```{r}
get_angle(life_df,items[1],items[2],'IRN')
```

```{r}
get_angle(life_df,items[1],items[2],'IND')

```

```{r}

```

```{r}
theta = acos(cor(female_vector,male_vector))
theta
```

